const catalog = {
  name: "ananke",
  title: "Ananke: GAIA on FIRE",
  descr:
    "<a href='https://arxiv.org/abs/1806.10564'>Sanderson et al 2018</a>.<br> Data release v- ____-__-__.<br> The ananke framework, which generates realistic synthetic stellar surveys from cosmological baryonic simulations, was used to create a set of synthetic phase-space surveys designed to resemble Data Release 2 of the Gaia astrometric survey from different solar viewpoints in the Latte suite of FIRE-2 simulations of Milky Way-mass galaxies. The synthetic surveys are described in detail in <a href='https://arxiv.org/abs/1806.10564'>Sanderson et al 2018</a>. The full dataset is available <a href='https://girder.hub.yt/#collection/5b0427b2e9914800018237da'>here</a>.\n",
  fields: [
    {
      dtype: "<i1", //python numpy type for generating python example code
      base: "i", // base type i = integer
      terms: true, // should it be displayed as a dropdown (yes)
      flag: false, // Displayed in the filter list by default. False is displayed but not required (has an all option), true is displayed and required (exclusive), null not displayed and not required. Are visible on first view, in true must have a value to see any data. We prepopulate with first value as a default.
      name: "galaxy",
      title: "galaxy",
      type: "byte", // raw data type (single byte integer)
      enum: ["m12i", "m12f", "m12m"], //only has these values
      descr: "Simulated galaxy",
      disp: true, //Displayed in table by default
    },
    {
      dtype: "<i1",
      base: "i",
      terms: true,
      flag: false,
      name: "lsr",
      title: "lsr",
      type: "byte",
      descr: "Local Standard of Rest (LSR) between 0-2",
      disp: true,
    },
    {
      dtype: "<i1",
      base: "i",
      terms: true,
      flag: false,
      name: "slice",
      title: "slice",
      type: "byte",
      descr: "slices between 0-9",
      disp: true,
    },
    {
      dtype: "<i8",
      base: "i",
      name: "source_id",
      dict: "GAIA_source_id",
      title: "Indices source_id",
      type: "long",
      descr: "Unique source identifier (per mock catalog)",
      disp: true,
    },
    {
      dtype: "<i8",
      base: "i",
      name: "random_index",
      dict: "GAIA_random_index",
      title: "Indices random_index",
      type: "long",
      descr: "Random index used to select subsets",
      disp: false,
    },
    {
      dtype: "<i8",
      base: "i",
      name: "parentid",
      title: "Indices parentid",
      type: "long",
      descr: "array index of the generating star particle in the snapshot file",
      disp: false,
    },
    {
      dtype: "<i2",
      base: "i",
      name: "partid",
      title: "Indices partid",
      type: "short",
      descr:
        "0 if phase-space coordinates are identical to generating star particle, 1 otherwise",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "ra",
      dict: "ppos_x",
      units: "deg",
      title: "Astrometry Coord ra",
      type: "double",
      descr: "Right ascension",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "ra_error",
      dict: "GAIA_ppos_x_error",
      units: "deg",
      title: "Astrometry Coord ra_error",
      type: "double",
      descr: "Standard error of right ascension",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "dec",
      dict: "ppos_y",
      units: "deg",
      title: "Astrometry Coord dec",
      type: "double",
      descr: "Declination",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "dec_error",
      dict: "GAIA_ppos_y_error",
      units: "deg",
      title: "Astrometry Coord dec_error",
      type: "double",
      descr: "Standard error of declination",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "parallax",
      dict: "parallax",
      units: "mas",
      title: "Astrometry parallax",
      type: "double",
      descr: "Parallax",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "parallax_error",
      dict: "GAIA_parallax_error",
      units: "mas",
      title: "Astrometry parallax_error",
      type: "double",
      descr: "Standard error of parallax",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "parallax_over_error",
      dict: "GAIA_parallax_over_error",
      title: "Astrometry parallax_over_error",
      type: "float",
      descr: "Parallax divided by its error",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmra",
      dict: "pmra",
      units: "mas/year",
      title: "Astrometry pmra",
      type: "double",
      descr: "Proper motion in right ascension direction",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmra_error",
      dict: "GAIA_pmra_error",
      units: "mas/year",
      title: "Astrometry pmra_error",
      type: "double",
      descr: "Standard error of proper motion in right ascension direction",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmdec",
      dict: "pmdec",
      units: "mas/year",
      title: "Astrometry pmdec",
      type: "double",
      descr: "Proper motion in declination direction",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmdec_error",
      dict: "GAIA_pmdec_error",
      units: "mas/year",
      title: "Astrometry pmdec_error",
      type: "double",
      descr: "Standard error of proper motion in declination direction",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "l",
      dict: "GAIA_l",
      units: "deg",
      title: "Astrometry l",
      type: "double",
      descr: "Galactic longitude",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "b",
      dict: "GAIA_b",
      units: "deg",
      title: "Astrometry b",
      type: "double",
      descr: "Galactic latitude",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "ra_true",
      units: "deg",
      title: "Phase Space ra_true",
      type: "double",
      descr: "true right ascension",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "dec_true",
      units: "deg",
      title: "Phase Space dec_true",
      type: "double",
      descr: "true declination",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "dmod_true",
      units: "mag",
      title: "Phase Space dmod_true",
      type: "double",
      descr: "true distance modulus",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "parallax_true",
      units: "mas",
      title: "Phase Space parallax_true",
      type: "double",
      descr: "true parallax",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmra_true",
      units: "mas/year",
      title: "Phase Space pmra_true",
      type: "double",
      descr: "true proper motion in right ascension direction",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pmdec_true",
      units: "mas/year",
      title: "Phase Space pmdec_true",
      type: "double",
      descr: "true proper motion in declination direction",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "radial_velocity_true",
      units: "km/s",
      title: "Phase Space radial_velocity_true",
      type: "double",
      descr: "true radial velocity",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "l_true",
      units: "deg",
      title: "Phase Space l_true",
      type: "double",
      descr: "true galactic longitude",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "b_true",
      units: "deg",
      title: "Phase Space b_true",
      type: "double",
      descr: "true galactic latitude",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "px_true",
      units: "kpc",
      title: "Phase Space px_true",
      type: "double",
      descr: "true position relative to LSR",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "py_true",
      units: "kpc",
      title: "Phase Space py_true",
      type: "double",
      descr: "true position relative to LSR",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "pz_true",
      units: "kpc",
      title: "Phase Space pz_true",
      type: "double",
      descr: "true position relative to LSR",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "vx_true",
      units: "km/s",
      title: "Phase Space vx_true",
      type: "double",
      descr: "true velocity relative to LSR",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "vy_true",
      units: "km/s",
      title: "Phase Space vy_true",
      type: "double",
      descr: "true velocity relative to LSR",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "vz_true",
      units: "km/s",
      title: "Phase Space vz_true",
      type: "double",
      descr: "true velocity relative to LSR",
      disp: false,
    },
    {
      reversed: true,
      dtype: "<f4",
      base: "f",
      name: "phot_g_mean_mag",
      dict: "GAIA_phot_g_mean_mag",
      units: "mag",
      title: "Photometry phot_g_mean_mag mag",
      type: "float",
      descr: "Extincted apparent G-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_g_mean_mag_error",
      dict: "GAIA_phot_g_mean_mag_error",
      units: "mag",
      title: "Photometry phot_g_mean_mag mag_error",
      type: "float",
      descr: "Standard error of G-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_g_mean_mag_true",
      units: "mag",
      title: "Photometry phot_g_mean_mag mag_true",
      type: "float",
      descr:
        "true (i.e. after extinction, but before error convolution) apparent G-Band mean magnitude",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_g_mean_mag_int",
      units: "mag",
      title: "Photometry phot_g_mean_mag mag_int",
      type: "float",
      descr:
        "intrinsic (i.e. after extinction, but before error convolution) apparent G-Band mean magnitude",
      disp: false,
    },
    {
      reversed: true,
      dtype: "<f4",
      base: "f",
      name: "phot_bp_mean_mag",
      dict: "GAIA_phot_bp_mean_mag",
      units: "mag",
      title: "Photometry phot_bp_mean_mag mag",
      type: "float",
      descr: "Extincted apparent G_Bp-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_bp_mean_mag_error",
      dict: "GAIA_phot_bp_mean_mag_error",
      units: "mag",
      title: "Photometry phot_bp_mean_mag mag_error",
      type: "float",
      descr: "Standard error of G_Bp-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_bp_mean_mag_true",
      units: "mag",
      title: "Photometry phot_bp_mean_mag mag_true",
      type: "float",
      descr: "true apparent of G_Bp-band mean magnitude",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_bp_mean_mag_int",
      units: "mag",
      title: "Photometry phot_bp_mean_mag mag_int",
      type: "float",
      descr: "intrinsic apparent of G_Bp-band mean magnitude",
      disp: false,
    },
    {
      reversed: true, // Displays x values on the left
      dtype: "<f4",
      base: "f",
      name: "phot_rp_mean_mag",
      dict: "GAIA_phot_rp_mean_mag",
      units: "mag",
      title: "Photometry phot_rp_mean_mag mag",
      type: "float",
      descr: "Extincted apparent G_Rp-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_rp_mean_mag_error",
      dict: "GAIA_phot_rp_mean_mag_error",
      units: "mag",
      title: "Photometry phot_rp_mean_mag mag_error",
      type: "float",
      descr: "Standard error of G_Rp-band mean magnitude",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_rp_mean_mag_true",
      units: "mag",
      title: "Photometry phot_rp_mean_mag mag_true",
      type: "float",
      descr: "true apparent of G_Rp-band mean magnitude",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "phot_rp_mean_mag_int",
      units: "mag",
      title: "Photometry phot_rp_mean_mag mag_int",
      type: "float",
      descr: "intrinsic apparent of G_Rp-band mean magnitude",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_rp",
      dict: "GAIA_bp_rp",
      units: "mag",
      title: "Photometry bp_rp",
      type: "float",
      descr: "BP - RP colour",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_rp_true",
      units: "mag",
      title: "Photometry bp_rp_true",
      type: "float",
      descr: "true BP - RP colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_rp_int",
      units: "mag",
      title: "Photometry bp_rp_int",
      type: "float",
      descr: "intrinsic BP - RP colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_g",
      dict: "GAIA_bp_g",
      units: "mag",
      title: "Photometry bp_g",
      type: "float",
      descr: "BP - G colour",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_g_true",
      units: "mag",
      title: "Photometry bp_g_true",
      type: "float",
      descr: "true BP - G colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "bp_g_int",
      units: "mag",
      title: "Photometry bp_g_int",
      type: "float",
      descr: "intrinsic BP - G colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "g_rp",
      dict: "GAIA_g_rp",
      units: "mag",
      title: "Photometry g_rp",
      type: "float",
      descr: "G - RP colour",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "g_rp_true",
      units: "mag",
      title: "Photometry g_rp_true",
      type: "float",
      descr: "true G - RP colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "g_rp_int",
      units: "mag",
      title: "Photometry g_rp_int",
      type: "float",
      descr: "intrinsic G - RP colour",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "a_g_val",
      dict: "GAIA_a_g_val",
      units: "mag",
      title: "Photometry a_g_val",
      type: "float",
      descr: "line-of-sight extinction in the G band, A_G",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "e_bp_min_rp_val",
      dict: "GAIA_e_bp_min_rp_val",
      units: "mag",
      title: "Photometry e_bp_min_rp_val",
      type: "float",
      descr: "line-of-sight reddening E(BP-RP)",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "lognh",
      units: "cm-2",
      title: "Extinction lognh",
      type: "float",
      descr: "log_10 equivalent H column density along line of sight to star",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "ebv",
      units: "mag",
      title: "Extinction ebv",
      type: "float",
      descr: "E(B-V) reddening, calculated from equivalent N_H",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "A0",
      units: "mag",
      title: "Extinction A0",
      type: "float",
      descr: "A_0 extinction at 550 nm, assuming R_v = 3.1",
      disp: false,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "radial_velocity",
      dict: "GAIA_radial_velocity",
      units: "km/s",
      title: "Spectroscopy radial_velocity",
      type: "double",
      descr: "Radial velocity",
      disp: true,
    },
    {
      dtype: "<f8",
      base: "f",
      name: "radial_velocity_error",
      dict: "GAIA_radial_velocity_error",
      units: "km/s",
      title: "Spectroscopy radial_velocity_error",
      type: "double",
      descr: "Radial velocity error",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "teff_val",
      dict: "GAIA_teff_val",
      units: "K",
      title: "Stellar Parameters teff_val",
      type: "float",
      descr: "stellar effective temperature",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "lum_val",
      dict: "GAIA_lum_val",
      units: "L_sun",
      title: "Stellar Parameters lum_val",
      type: "float",
      descr: "stellar luminosity",
      disp: true,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "mact",
      units: "\\(M_\\odot\\)",
      title: "Stellar Parameters mact",
      type: "float",
      descr: "current stellar mass",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "mtip",
      units: "\\(M_\\odot\\)",
      title: "Stellar Parameters mtip",
      type: "float",
      descr: "mass of a star at tip of giant branch for given age, metallicity",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "mini",
      units: "\\(M_\\odot\\)",
      title: "Stellar Parameters mini",
      type: "float",
      descr: "stellar mass on zero-age main sequence",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "age",
      units: "log yr",
      title: "Stellar Parameters age",
      type: "float",
      descr:
        "log_10 stellar age; identical for all stars generated from the same particle",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "logg",
      units: "log cgs",
      title: "Stellar Parameters logg",
      type: "float",
      descr: "surface gravity",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "feh",
      units: "dex",
      title: "Abundances feh",
      type: "float",
      descr: "[Fe/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "alpha",
      units: "dex",
      title: "Abundances alpha",
      type: "float",
      descr: "[Mg/Fe]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "carbon",
      units: "dex",
      title: "Abundances carbon",
      type: "float",
      descr: "[C/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "helium",
      units: "dex",
      title: "Abundances helium",
      type: "float",
      descr: "[He/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "nitrogen",
      units: "dex",
      title: "Abundances nitrogen",
      type: "float",
      descr: "[N/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "sulphur",
      units: "dex",
      title: "Abundances sulphur",
      type: "float",
      descr: "[S/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "oxygen",
      units: "dex",
      title: "Abundances oxygen",
      type: "float",
      descr: "[O/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "silicon",
      units: "dex",
      title: "Abundances silicon",
      type: "float",
      descr: "[Si/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "calcium",
      units: "dex",
      title: "Abundances calcium",
      type: "float",
      descr: "[Ca/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "magnesium",
      units: "dex",
      title: "Abundances magnesium",
      type: "float",
      descr: "[Mg/H]",
      disp: false,
    },
    {
      dtype: "<f4",
      base: "f",
      name: "neon",
      units: "dex",
      title: "Abundances neon",
      type: "float",
      descr: "[Ne/H]",
      disp: false,
    },
  ],
};
const query = {
  seed: null,
  offset: 0,
  sort: [],
  aggs: [],
  limit: 0,
  filter: [],
  sample: 1,
  fields: [
    "galaxy",
    "lsr",
    "slice",
    "source_id",
    "ra",
    "ra_error",
    "dec",
    "dec_error",
    "parallax",
    "parallax_error",
    "parallax_over_error",
    "pmra",
    "pmra_error",
    "pmdec",
    "pmdec_error",
    "l",
    "b",
    "phot_g_mean_mag",
    "phot_g_mean_mag_error",
    "phot_bp_mean_mag",
    "phot_bp_mean_mag_error",
    "phot_rp_mean_mag",
    "phot_rp_mean_mag_error",
    "bp_rp",
    "bp_g",
    "g_rp",
    "a_g_val",
    "e_bp_min_rp_val",
    "radial_velocity",
    "radial_velocity_error",
    "teff_val",
    "lum_val",
  ],
};
